SECRET_TOKEN: "SECRET_TOKEN_TO_REPLACE"
SMTP_ADDRESS: "SMTP_ADDRESS_TO_REPLACE"
SMTP_PORT: SMTP_PORT_TO_REPLACE
SMTP_DOMAIN: "SMTP_DOMAIN_TO_REPLACE"
SMTP_USER_NAME: "SMTP_USER_NAME_TO_REPLACE"
SMTP_PASSWORD: "SMTP_PASSWORD_TO_REPLACE"
SMTP_AUTHENTICATION: "SMTP_AUTHENTICATION_TO_REPLACE"
HOST_URL: "HOST_URL_TO_REPLACE"
FROM: "SMTP_FROM_TO_REPLACE"